spring.application.name=TempShop


spring.datasource.url=jdbc:postgresql://db.adihwadrjrqtrbctnchz.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=999107201012606

# Driver class
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings (optional but commonly used)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true